name: Generate VPN Release Branch Dashboard Data
on:
  pull_request:
    branches:
      - main

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  generate-dashboard-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Nodejs script to gather pipeline status
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: node release.js
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: merge updated details to main
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions"
          git add .
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "Chore (automated): update workflow details $(date)"
            git push origin main
          fi